name = "Geert en Jordy Server"
author = "kinggeert, jordy_vogeltjes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66eda8942a0e414d0487ee3466dac2ecfb0ec7a1a350f7a0085f233587c8c754"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
