name = "Geert en Jordy Server"
author = "kinggeert, jordy_vogeltjes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe813fdb83db8bf19858984fb10f59d1b94f3065224db7ec393a2be993383f58"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5"]
