name = "Geert en Jordy Server"
author = "kinggeert, jordy_vogeltjes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba3ec52f218d7523b2fa38957363547c721f8d7b9696c336e75c2430873c4e16"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
